name: main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :app:assembleRelease
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        # don't upload the artifacts if it's a pull request
        with:
          path: './app/build/outputs/*'
          name: build_output.zip
